export const FETCH_PUBLIC_PROFILE_SUCCESS = 'FETCH_PUBLIC_PROFILE_SUCCESS'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_OUT = 'LOGIN_OUT'
export const SALAM = 'SALAM'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
